version: "3.8"

services: 
  app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4000:4000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    links:
      - mysql_server
    environment: 
      - MYSQL_HOST=mysql_server
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=photos_db
    networks:
      - internalnet

  mysql_server:
    image: mysql
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment: 
      - MYSQL_DATABASE=photos_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    restart: always
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge


    